name: 'dbt_tags'
vars:
  # dbt_tags__database: common  # optional, target.database if not specified
  # dbt_tags__schema: tags      # optional, target.schema if not specified
  dbt_tags__resource_types: ["model", "snapshot", "source"] # mandatory, find tags for only configured dbt resource types 
  # dbt_tags__allowed_tags: []  # optional, allow all