sources:
  - name: mart_jaffle_shop
    database: POC_IL_SM
    schema: DAT_CLOUD_PROD
    tables:
      - name: customers
        columns:
          - name: customer_id
      - name: orders
        columns:
          - name: customer_id
            tests:
              - relationships:
                  to: source('mart_jaffle_shop', 'customers')
                  field: customer_id